// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicPostUpdate,
  DefaultPostUpdateProps
} from "./plasmic/copy_of_supabase/PlasmicPostUpdate";
import { HTMLElementRefOf } from "@plasmicapp/react-web";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface PostUpdateProps extends Omit<DefaultPostUpdateProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultPostUpdateProps altogether and have
// total control over the props for your component.
export interface PostUpdateProps extends DefaultPostUpdateProps {}

function PostUpdate_(props: PostUpdateProps, ref: HTMLElementRefOf<"div">) {
  // Use PlasmicPostUpdate to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicPostUpdate are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, we are just piping all PostUpdateProps here, but feel free
  // to do whatever works for you.

  return <PlasmicPostUpdate root={{ ref }} {...props} />;
}

const PostUpdate = React.forwardRef(PostUpdate_);
export default PostUpdate;
